### ISSUE TITLE
Data Validation Plan for Dataset Columns

### ISSUE THREAD

**Issue by javiermtzo99** [UBC-MDS/diabetes_predictor_py#18]
Hello team,
I want to discuss our approach to data validation for the dataset. Are we planning to create specific validation checks for each column? If so, I would like to propose the following descriptions for the dataset's columns:

**Column Descriptions:**

- [ ] `Pregnancies`: Number of times pregnant
- [ ] `Glucose`: Plasma glucose concentration after 2 hours in an oral glucose tolerance test
- [ ] `BloodPressure`: Diastolic blood pressure (mm Hg)
- [ ] `SkinThickness`: Triceps skin fold thickness (mm)
- [ ] `Insulin`: 2-Hour serum insulin (mu U/ml)
- [ ] `BMI`: Body mass index (weight in kg/(height in m)^2)
- [ ] `DiabetesPedigreeFunction`: Diabetes pedigree function
- [ ] `Age`: Age (years)
- [ ] `Outcome`: Class variable (0 or 1) — 268 of 768 are 1, the others are 0

**Checklist for Data Validation:**
For all columns:

- [ ]  Correct data file format
- [ ]  Correct column names
- [ ]  No empty observations
- [ ]  Correct data types
- [ ]  No duplicate observations
- [ ]  No outlier or anomalous values (Pending discuss on how to identify an outlier)

For specific columns:

`Outcome`:

- [ ]  Validate that values are restricted to 0 or 1

Additionally, where do you think would be the best place in the README file to document the checklist for input data validation? Should it be a standalone section like "Data Requirements", or integrated into an existing section, such "Usage Instructions"? Your thoughts and suggestions are greatly appreciated!

**Comment by JennyonOort** [comment]
From @javiermtzo99 (from Slack): I think it would be great to add a text cell with a checklist of our data validations in the analysis.ipynb

**Comment by JennyonOort** [comment]
I see your point and am not against this. This will in markdown format then?

I would say we can ask Tiff today because 1) I didn't see this list in her analysis notebook and 2) thinking from a reader's perspective, we want to communicate the findings effectively and succinctly than purely presenting to them the work we had done so the context of a checklist checked off might be out of place.

We can also see if others would like to chip in.

**Comment by InderKhera** [comment]
This is also one of the questions I wanted to ask Tiffany during office hours. I was thinking we put the checklist in either our analysis or maybe a section of our READ me where we discuss what our data validation procedures check off.

**Comment by InderKhera** [comment]
I spoke with Tiffany today during office hours. She mentioned the data validation checklist was not required it is just a good way for us to visualize the validations that are needed to be completed as we are working on our analysis.
