### ISSUE TITLE
Mamba Issue to work on Docker process

### ISSUE THREAD

**Issue by JennyonOort** [UBC-MDS/diabetes_predictor_py#26]
Hi team, 

As discussed on potential resolutions for the mamba issue, I am providing here the version of python I used for my individual assignment and has mamba properly working.

```
$ python --version
Python 3.11.9
```

**Comment by JennyonOort** [comment]
Downgrading python version to solve compatibility issue for mamba could be worth trying for.

**Comment by kuo4230** [comment]
issue fixed by downgrading to Python version 3.11
