### ISSUE TITLE
Mid-Week Check-In Meeting

### ISSUE THREAD

**Issue by JennyonOort** [UBC-MDS/diabetes_predictor_py#27]
Hi Team,

Below are the meeting summary for the mid-week check in that we added for this week:

- Docker process on halt due to the mamba error and inability to properly add deep-check packages to `environment.yml`

A couple resolutions proposed:
1) instead of adding dependencies directly in the `environment.yml` file, try installing the deep-checks package in the activated `diabetes-analysis` environment and then export environment file.
2) try downgrading Python version to 3.11 to resolve compatibility issue with mamba
3) Other team members to check if environment and docker file properly runs on their machine to determine if it is person specific computer / machine issue or systematic `environment.yml` file or Docker issue

- Data validation analysis - both pandera and deep-checks - to be done tonight

Team to reconvene at Tiffany's office hour on Thursday to update latest progress and resolve any remaining issues.

For any updates to the issues or resolution found, please kindly update the team here directly.

**Comment by kuo4230** [comment]
some updates after meeting:

1) environment.yml file updated with downgraded python version to 3.11.10
2) associated conda-lock files were also being updated per new version of environment.yml
3) successfully built and tested docker image and container in JK's local laptop 
4) changes have been merged to main and git action created to successfully ran docker publish workflow

Current docker image: docker pull jk112358/diabetes_predictor_py (https://hub.docker.com/r/jk112358/diabetes_predictor_py)

**Comment by kuo4230** [comment]
Please feel free to pull and test out the newly updated environment. It should now support pandera & deepchecks as well.
