### ISSUE TITLE
Docker-compose tagging Issue

### ISSUE THREAD

**Issue by JennyonOort** [UBC-MDS/diabetes_predictor_py#36]
Hi Jess, 

Given the pull request review has been closed, I am opening a new issue here with regards to tagging to the latest image (i.e. the latest virtual container) so that our environment may not be updated properly, and the added image tagging commands in `docker-publish.yml` will not give an error but it will not properly update anything. 

I've attached the snapshot of `docker-compose.yml` from Tiff's example. We need the `: <SHA>` from Docker hub to make sure we start off with the latest version of the image. 

![image](https://github.com/user-attachments/assets/6ab720df-bcdb-4f1f-828b-81f60d0d4b61)

**Comment by JennyonOort** [comment]
@kuo4230

**Comment by JennyonOort** [comment]
To add, the reason that we are not spotting errors from docker-compose.yml is because we have not used the file in our set-up process directions. docker-compose is equivalent to the command docker run but allowed for much more configurations and way less typing, so much less risk of mistakes. We have completely skipped the usage of file with our instructions.

Snapshot of README.md on how `docker-compose` should be run:
![image](https://github.com/user-attachments/assets/fefbcdc9-5f3a-47cd-8fbf-93f6f4020e65)

**Comment by kuo4230** [comment]
issue fixed by #42 #43 PRs
