### ISSUE TITLE
Task Assignment - Milestone 3

### ISSUE THREAD

**Issue by kuo4230** [UBC-MDS/diabetes_predictor_py#55]
**Meeting Details**
Date: 12/2
Time: 2-4pm
Location/Platform: 522 lab

**Attendees:** Jessica, Inder, Jenny, Javier, 

**Agenda**
Task assignment & set deadline

**Key Points:**
- Task breakdown
- Milestone 2 reflection

**Decisions Made:**
Task assigned 

**Task breakdown:**

README.md: @InderKhera 

Environment update (environment.yml, dockerfile, conda locks, docker container): @kuo4230

Scripts: 
- Data loading: @JennyonOort 
- EDA: @JennyonOort 
- Schema validations: @JennyonOort 
- Deepchecks: @JennyonOort 
- Splits and Preprocessing: @javiermtzo99 
- Model fitting-hyperparameter optimization: @javiermtzo99 
- Model evaluation - test results: @InderKhera 

Prepare Report:
- Convert the report to a .qmd file: @kuo4230 
- Edit the report to focus on narration, figures, and tables without visible code: @kuo4230 
- Test rendering to HTML and PDF formats: @kuo4230 

Creating releases: @InderKhera 
Code & process review: all members

**Role designation (scribe / proofreader)**
Scriber: @kuo4230 
Proofreader: @InderKhera

**Comment by JennyonOort** [comment]
qmd reports tasks ultimately completed as a team.
