### ISSUE TITLE
Additional environments update

### ISSUE THREAD

**Issue by JennyonOort** [UBC-MDS/diabetes_predictor_py#56]
Hi @kuo4230 ,

As I am creating the scripts, below are some additional packages needed for environment / Docker update:

```
- requests=2.31.0
```
Upon env and Docker updated, I should be able to test the scripts out and then can create pull requests to merge to main branch. Let me know when you would have flexibility to do so, alternatively I can also take the responsiblity to do so, just let me know.

Thank you!

**Comment by kuo4230** [comment]
adding package in environment.yml as well as updated file of conda lock
tested on my local laptop --> success

**Comment by JennyonOort** [comment]
Great, thank you!
