### ISSUE TITLE
Regarding duplicate dependencies in builders & `environment.yml`

### ISSUE THREAD

**Issue by JennyonOort** [UBC-MDS/diabetes_predictor_py#69]
![image](https://github.com/user-attachments/assets/bd5dc89e-d36a-47aa-9090-9256a4c7b7e3)

Hi team, 

I am posting this issue and we collaborately discuss as a group. Essentially, there are some dependencies that should be installed in base environment (i.e. globally) so it is possible to create & run Docker, conda-lock files, and virtual environement as needed. Those packages included in `environment.yml` are environment specific packages to reproduce analysis. 

With that being said, these dependencies should be "global" dependencies.
![image](https://github.com/user-attachments/assets/2a531bf3-f7da-4e21-b2dd-1ad6725ac2bd)

And the following should be removed from `environment.yml` file, along with step 3 (see above), where we create virtual env from `environment.yml` as that will be a duplicate step to creating env from conda-lock.

```
dependencies:
  - jupyterlab=4.2.6
  - conda-lock=2.5.7
  - mamba=1.5.11
```
Kindly let me know if there are any questions / concerns with regards to this. Happy to discuss collaborately as a team. 

Best Regards,
Jenny

**Comment by javiermtzo99** [comment]
I actually agree with you. The thing is, if we want to add another library, the builder would work well in that situation. The builder is typically used for restarting and downloading everything in a single script. However, for those of us who are constantly working on the project, we should only run `docker-compose up`.

**Comment by JennyonOort** [comment]
TO REVISIT AGAIN FOR MILESTONE 4

**Comment by JennyonOort** [comment]
Maintain Docker environment.
