### ISSUE TITLE
Meeting Minutes: Zoom Standup on Dec 7th, 2024

### ISSUE THREAD

**Issue by kuo4230** [UBC-MDS/diabetes_predictor_py#72]
Meeting Details
Date: 12/7/2024
Time: 5-6pm
Location/Platform: Zoom

Attendees: Jessica, Inder, Jenny, Javier,

Agenda:
Report progress, review PRs, and resolve issues

Key Points:
- Inder's PRs were reviewed and approved during the meeting
- Jessica will require help from the team to update the qmd file; Jenny offered to help with updating the part she's responsible in the analysis, the rest of the team will also provide the code/script output and send to Jessica to be insert into the qmd file
- Jessica has uploaded the latest qmd and html file for everyone's reference
- Inder will work on updating the README file on Sunday morning before submission

The aim is to have everything mostly done by Sunday morning and do additional touch ups on Sunday morning.

**Comment by JennyonOort** [comment]
Should more closely follow interim deadlines so there is sufficient time to check. Understand it is quiz week.
