### ISSUE TITLE
Close to Final Report

### ISSUE THREAD

**Issue by JennyonOort** [UBC-MDS/diabetes_predictor_py#91]
Team, here is the latest report. Went through all feedback and fixed all consolidation issues with regards to disconnection in scripts:
https://ubc-mds.github.io/diabetes_predictor_py/reports/diabetes_analysis.html

Would be really nice to get a fresh pair of eyes to read through in the AM to spot any remaining typos or grammar issues. In the meantime, I've created a release and submitted on Gradescope just so we already have a version

Also, would be great if one of you can please try building the Docker from scratch again. Essentially following the steps in latest README and replicate through the analysis.

Lastly, the below is the grading rubric for Milestone 4. Let us check against.

Cheers!

![image](https://github.com/user-attachments/assets/00194e64-edab-4f5e-a841-f67a453a8e67)

**Comment by kuo4230** [comment]
Sorry Jenny, I still haven't recovered fully yet. I'll see if anyone else can jump in, if not, I can take a quick peak this evening.

**Comment by InderKhera** [comment]
Hi Jenny, 

I have deleted the docker image and rebuilt the docker from scratch, everything appears to work as expected, the Makefile along with the functions and scripts as well. I have also gone over our amendments and the analysis as well as taken a look at the READ.me file and I did not find any grammatical errors. Great Work!
